### ISSUE TITLE
Cloning UCTB Repository Fails with SSH Public Key Error

### ISSUE THREAD

**Issue by xubin04** [uctb/UCTB#41]
It appears that my graphics card, the 3090, does not seem to support the older version of TensorFlow 1.13.1 very well. Therefore, following the instructions in the tutorial, I tried to execute git clone git@github.com:uctb/UCTB.git, but encountered an error message:

Cloning into 'UCTB'...
The authenticity of host 'github.com (20.205.243.166)' can't be established.
ECDSA key fingerprint is SHA256:p2QAMXNIC1TJYWeIOttrVc98/R1BUFWu3/LiyKgUfQM.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,20.205.243.166' (ECDSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by Liyue-Chen** [comment]
Dear xubin04, 

Thanks for your interest in UCTB. According to your log, I think you may need to check your SSH keys. Here are several things that may help:

* GitHub uses SSH keys for authentication when cloning repositories via SSH. You need to ensure that your local SSH key is added to your GitHub account.
* To check if your SSH key is already added, visit your GitHub account settings (https://github.com/settings/ssh/new) and look for your public key in the list of SSH keys.
* If your key is not listed, you'll need to generate a new SSH key pair (if you haven't already) and add the public key to your GitHub account. You can generate a new SSH key pair using the ssh-keygen command in your terminal.

If you still cannot clone UCTB by command line, I recommend you download the source code on GitHub directly.

**Comment by xubin04** [comment]
Thank you for your timely reply. I have downloaded the source code successfully with the code ''git clone https://github.com/uctb/UCTB.git''. It might be because the instructions you provided in the tutorial are not quite suitable, but that's not important. What I want to ask is, since your project UTCB and One4All-ST include some code based on TensorFlow, I am unable to run the code you provided normally due to some hardware reasons and the widely criticized configuration issues with TensorFlow. So, I would like to ask if you would consider providing a library purely based on PyTorch so that more people can reproduce and follow your work. I believe this would be of great help to the entire community and would also bring greater impact to your work.

**Comment by Liyue-Chen** [comment]
We are immensely appreciative of your insightful advice regarding the release of the PyTorch-based toolbox. Actually, we are working on the torch version. In the interim, we kindly suggest considering the installation of an additional package to enable compatibility with 30/40 NVIDIA chips. For detailed instructions, please refer to our documentation at: https://uctb.github.io/UCTB/md_file/installation.html#high-version-gpu-framework-support 
If you encounter any issues, please feel free to let us know.

**Comment by xubin04** [comment]
> 我们非常感谢您关于发布基于 PyTorch 的工具箱的有见地的建议。实际上，我们正在开发火炬版本。在此期间，我们建议您考虑安装一个额外的软件包，以实现与30/40 NVIDIA芯片的兼容性。有关详细说明，请参阅我们的文档： https://uctb.github.io/UCTB/md_file/installation.html#high-version-gpu-framework-support 如果您遇到任何问题，请随时告诉我们。

Thank you for your response. The timely release of the PyTorch version would be of great help to me. The main issues with the current version are manifested when I run the experiment file of One4All-ST, and the following error occurs:Traceback (most recent call last):
  File "/home/xb/One4All-ST/exp.py", line 90, in <module>
    ArbFlow_Obj.fit(closeness_feature=data_loader.train_closeness,
  File "/home/xb/One4All-ST/UCTB/model_unit/BaseModel.py", line 520, in fit
    train_output = self._run(feed_dict=train_dict_mini_batch.get_batch(),
  File "/home/xb/One4All-ST/UCTB/model_unit/BaseModel.py", line 417, in _run
    outputs = self._session.run(output_tensor_list, feed_dict=feed_dict_tf)
  File "/home/xb/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 955, in run
    result = self._run(None, fetches, feed_dict, options_ptr,
  File "/home/xb/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1179, in _run
    results = self._do_run(handle, final_targets, final_fetches,
  File "/home/xb/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1358, in _do_run
    return self._do_call(_run_fn, feeds, fetches, targets, options,
  File "/home/xb/.local/lib/python3.8/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution execution plan. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d_2/Conv2D (defined at /.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
         [[add_18/_289]]
  (1) Unknown: Failed to get convolution execution plan. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d_2/Conv2D (defined at /.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'conv2d_2/Conv2D':
  File "/One4All-ST/exp.py", line 82, in <module>
    ArbFlow_Obj.build()
  File "/One4All-ST/UCTB/model/ArbFlow_paradigm.py", line 105, in build
    residual_input = tf.layers.conv2d(conf, filters=self._conv_filters,
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/util/deprecation.py", line 330, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/layers/convolutional.py", line 424, in conv2d
    return layer.apply(inputs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/util/deprecation.py", line 330, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/layers/base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 854, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/autograph/impl/api.py", line 234, in wrapper
    return converted_call(f, options, args, kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/autograph/impl/api.py", line 439, in converted_call
    return _call_unconverted(f, args, kwargs, options)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/autograph/impl/api.py", line 330, in _call_unconverted
    return f(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/keras/layers/convolutional.py", line 201, in call
    outputs = self._convolution_op(inputs, self.kernel)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/ops/nn_ops.py", line 1176, in __call__
    return self.conv_op(inp, filter)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/ops/nn_ops.py", line 662, in __call__
    return self.call(inp, filter)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/ops/nn_ops.py", line 245, in __call__
    return self.conv_op(
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/ops/nn_ops.py", line 2044, in conv2d
    return gen_nn_ops.conv2d(input,  # pylint: disable=redefined-builtin
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/ops/gen_nn_ops.py", line 1067, in conv2d
    _, _, _op = _op_def_lib._apply_op_helper(
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/op_def_library.py", line 792, in _apply_op_helper
    op = g.create_op(op_type_name, inputs, dtypes=None, name=scope,
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/util/deprecation.py", line 513, in new_func
    return func(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3356, in create_op
    return self._create_op_internal(op_type, inputs, dtypes, input_types, name,
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 3418, in _create_op_internal
    ret = Operation(
  File "/.local/lib/python3.8/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()   
Instead of repeatedly dealing with the configuration issues of TensorFlow, I am more looking forward to the PyTorch version of the code you will release, which will once and for all solve the environmental configuration problems. I wish you a smooth development process.
